version: '3'
services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: language_model_gateway
    environment:
      DEBUG_METRICS: 0
      DD_TRACE_ENABLED: "false"
      LOG_LEVEL: INFO
      AGENT_URL: 'http://host.docker.internal:5055/api/v1'
      OPENAI_AGENT_URL: 'http://host.docker.internal:5055/api/v1'
      DEFAULT_PATIENT_ID: "eEooRVLYdWIW753OhZUd1dgxQRny4KCo6fiH-13lY0043"
#      DEFAULT_WEB_SEARCH_TOOL: "duckduckgo_search"
      DEFAULT_WEB_SEARCH_TOOL: "google_search"
      RUN_TESTS_WITH_REAL_LLM: 0
      IMAGE_GENERATION_PATH: "/usr/src/language_model_gateway/image_generation"
#      IMAGE_GENERATION_PATH: "s3://bwell-dev-data-science-ue1/openwebui/image_generation/"
      IMAGE_GENERATION_URL: "http://localhost:5050/image_generation"
      MODELS_OFFICIAL_PATH: "/usr/src/language_model_gateway/language_model_gateway/configs/chat_completions/official"
      MODELS_TESTING_PATH: "/usr/src/language_model_gateway/language_model_gateway/configs/chat_completions/testing"
#      MODELS_ZIP_PATH: "https://github.com/icanbwell/language-model-gateway-configuration/zipball/main/"
#      MODELS_OFFICIAL_PATH: "configs/chat_completions/official"
#      MODELS_TESTING_PATH: "configs/chat_completions/testing"
#      MODELS_OFFICIAL_PATH: "https://github.com/icanbwell/language-model-gateway-configuration/tree/main/configs/chat_completions/official"
#      MODELS_TESTING_PATH: "https://github.com/icanbwell/language-model-gateway-configuration/tree/main/configs/chat_completions/testing"
      MODELS_PATH_BACKUP: "/usr/src/language_model_gateway/language_model_gateway/configs/chat_completions"
      CONFIG_CACHE_TIMEOUT_SECONDS: 120
      PROVIDER_SEARCH_API_URL: "https://provider-search.prod.icanbwell.com/graphql"
      # Number of worker process to run
      NUM_WORKERS: 1
      AWS_REGION: 'us-east-1'
      HELP_KEYWORDS: "help;/help;aid"
      LOG_INPUT_AND_OUTPUT: 1
      DEFAULT_MODEL_PROVIDER: "bedrock"
      DEFAULT_MODEL_NAME: "us.anthropic.claude-3-5-haiku-20241022-v1:0"
    env_file: docker.env
    ports:
      - '5050:5000'
    volumes:
    - ./:/usr/src/language_model_gateway/:cached
      # uncomment this for testing AWS models and the docker.env above (need the AWS_CREDENTIALS_PROFILE env var)
    - ~/.aws/:/etc/appuser/.aws/
    healthcheck:
      test: curl --fail -s http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - web

networks:
  web:
    driver: bridge
