name: Deploy to DockerHub

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  IMAGE_NAME: language_model_gateway
#  REPOSITORY_URL: ##############.dkr.ecr.us-east-1.amazonaws.com

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - name: AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-region: us-east-1
#
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - name: Create builder
        run: |
          docker buildx create --use

      - name: Inspect builder
        run: |
          docker buildx inspect --bootstrap

      - name: Build, tag, and push image to Amazon ECR
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:$TAG \
            -t $IMAGE_NAME:latest \
            --push \
            -f Dockerfile .
